### ISSUE TITLE
[Feature Request] Customize route action segments

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/ideas#107]
# Feature Request

### What's the feature you think Backpack should have?

Some customers cannot be happy if routes are ending with verbs, like "show" or "create" or "edit".
In some circustances, it's due to need to translate for example "edit" in "modifica".
> I suggest to do not append at all a verb for get the list operation, or to allow this in future

So i suggest to make configurable all of these verbs

### Have you already implemented a prototype solution, for your own project?

Actually not, but it do not require a lot of works

Of course this require
- add a 'route_verb_suffix' or similar entry to each of action in config/backpack/base.php 
- read these values defaulting to actuals (to be backward-compatible) in every place where we construct routes
  -  every crud buttons, (and I suggest to migrate to route names instead of using url !!!)
  -  every setupShowRoutes and similar

### Do you see this as a core feature or an add-on?

Core feature, becase no addon can overwrite these strings

**Comment by tabacitu** [comment]
Hi @realtebo 

I think that's interesting. I've never had anyone complain that the URLs themselves are verbs or aren't translated though - it's the first time I hear about it.

Personally I think that would be overkill for an admin panel. Especially since the trend for browsers now is to hide the URL entirely, and only show the domain name. If that trend continues (as it seems now), people will only see the domain, never the URL, so they will only interact with the URL when they need to copy-paste it (which is probably the case now too). 

From that point of view, yes, when you copy-paste the URL you see some English and a verb, and it seems like you're seeing the soft underbelly of the website, but... you _are_. The URL is very similar to View Page Source in that respect - it's an intrinsic part of the website, which is public for everyone with access to see, because that's how this technology works.

I think in 99% of all admin panels, changing URL verbs to smth else, or translating the URLs is not needed - I'm saying that because it's the first time I hear someone suggesting it. **Adding this feature involves an easy-to-do but very intrusive breaking change, in a lot of places, and an upgrade guide to tell everybody to change their own code. And... I don't think this feature is worth all that trouble, to be honest. I think we would only frustrate and inconvenience the 99.9% of devs who don't need this, for the 0.1% that might use it - and that's a bad tradeoff.**

**Of course, I might be wrong - I often am 😀 So let's leave this issue open for now - see what others thing, if anybody else searches or stumbles upon it and says we should reconsider and do it.** But for now... I'm afraid my opinion is that this is a very niche feature and we shouldn't include it in the core. Which is sad, I know, because it can _only_ be in the core... And I do want Backpack to be as customisable as possible, I know how specific requirements can get and I want Backpack to cater to anything (ANYTHING!).

What I recommend you do until we close/solve this @realtebo is to create your own operation traits, that extend the traits in Backpack, and overwrite the `setupRoutes()` methods. Then use _your_ operation traits, instead of the ones provided by Backpack, everywhere you want that feature. That should provide you with the feature you need, for the time being.

Sorry if you're disappointed with the answer @realtebo ... This is a tough one. Let me know if you disagree with my judgement.

Cheers!

**Comment by realtebo** [comment]
I agree with you, except in fact that is not a breaking chang, if the patch is done with actual defaults in mind.

We are still working on this customer and so one day or later we will face the issue raised from he again; so I don't exclude one day we'll post a patch. Actually, we've not realized it. (and not intention to do it, like you, if absolutely not needed)

**Comment by tabacitu** [comment]
Hey @realtebo - I'm here with an update 😀 Present me still thinks it's not worth translating the URLs... So I'm going to close this issue. Thanks for letting us know though, if you do end up needing this feel free to reply here and we'll help you through it - it's an interesting nut to crack 😅 But since the overwhelming majority of projects won't need this, I vote to not make it any easier than it is now... I hope you understand. 

Cheers!
