### ISSUE TITLE
[Feature Request] Stop showing the "security newsletter" modal so often in the docs

### ISSUE THREAD

**Issue by joelmellon** [Laravel-Backpack/ideas#130]
The security newsletter modal is incredibly annoying. I've signed up, I know about it, I'm good.

I know it doesn't show up if I'm logged in, but I get logged out often, so any time I need to check documentation real quick, I'm prompted with this modal. It seems to come back in an hour or two as well, so it's incredibly frustrating if I'm in the documentation all day.

Please add a long term cookie saying I've seen it, dismissed it, or even just increase the site's session timeout for registered users to 30 days or something. (Google never logs people out, and the world loves Google.)

<img width="1175" alt="Screen Shot 2022-03-22 at 2 39 23 PM" src="https://user-images.githubusercontent.com/13803216/159580706-67853611-509f-44f9-a473-e12651e3236c.png">

# 🙏

**Comment by pxpm** [comment]
@joelmellon it must be something on your side. I'm logged for months on https://backpackforlaravel.com

Anyway, I agree that atleast we can have a bigger buffer for the message to show-up again, I guess 30 days it's fine too. 

ping @tabacitu

**Comment by tabacitu** [comment]
I agree, must be something on his side. But he's not the first person to report this, so I'll investigate. I was thinking of removing it entirely, in favor of a note at the top or bottom of the page... that should be less annoying...

Will do, thank you!

**Comment by joelmellon** [comment]
Thanks for the reply guys. I imagined it was a bit of a touchy subject, and I honestly didn't expect such a positive response. You guys are awesome. 👊

**Comment by joelmellon** [comment]
Update: I'm logged out today, and I haven't restarted my browser in quite a while, so I decided to take a peak at the cookies.

The `backpack_session` cookie expires in 24 hours, having logged in just now at `Sat, 25 Mar 2022 19:16:08 GMT`:
<img width="300" alt="Screen Shot 2022-03-25 at 12 16 41 PM" src="https://user-images.githubusercontent.com/13803216/160187121-cc4ce119-0fb1-412e-a9ee-c2ff7be8f4f9.png">

Also, the `hide_login_modal` cookie is only for 30 minutes 😢 having dismissed the modal at `Sat, 25 Mar 2022 19:11:14 GMT`:
<img width="301" alt="Screen Shot 2022-03-25 at 12 14 08 PM" src="https://user-images.githubusercontent.com/13803216/160186721-170b5c2e-ea51-4652-adbb-aa8a4293bb93.png">

**Comment by tabacitu** [comment]
Ouch! Thanks for the update @joelmellon . You're right, of course, sorry for all the frustration.

Looks like our session was set to expire using an ENV variable... after only 24h (!!!). It's 100% my fault, I probably forgot to switch it back after we fixed something. So what happened was:
- when we looked at the session expire time, we saw 30 days in the code (not 24h), so we thought the session is ok;
- since you didn’t visit the Backpack website every 24h… you got the popup every time;
- since we visit Backpack every day, so we didn’t see it;

I imagine how frustrating this must have been for you... and others... 🤦‍♂️ 
Can't believe we kept it like this for so long... no idea how long either.

I've changed it to 30 days. So after you login next time, you shouldn't be getting it.
Thanks a lot for letting us know about this. Let me know if this doesn't fix it for you, and we'll reopen.

Cheers!

PS. I'm still considering turning this into a banner, rather than a modal, to be less intrusive... But that would take a lot more time, to design an everything, so this quick fix should do it for now.

**Comment by joelmellon** [comment]
@tabacitu  Out of curiosity, did you change the login session time or the newsletter session time or both?

I'm sure you guys do want to remind people to sign up regularly, so my concern if I understand you correctly, is if a guest visits the site at least every 30 days, and if they've ever dismissed the newsletter popup, they would never see it again, right? That's probably too extreme.

Anyway, I just hope I didn't massively reduce the number of sign-ups you guys get. 😬

**Comment by tabacitu** [comment]
Nope - 3 days for the modal close, 30 days for logged in users. My thinking was that if you're just trying Backpack out... you'll do it for less than 3 days... and if you do decide to use it, you'll probably come back after 3 days... So I hope these numbers provide the right balance between getting people to sign up to it... and not being annoying 🤞 We'll see, I guess 😀 Thank you!
