### ISSUE TITLE
"Mentions" section / channel / stream / bot

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/ideas#165]
I have a few things set up, so that I receive everything that shows up online about Backpack:
- I'm subscribed to [the StackOverflow RSS feed](https://stackexchange.com/filters/253497/backpack-for-laravel)
- I have Google Alerts
- I use a paid service to watch Fb, Tw, Reddit and the web in general for any mentions

This results in a constant stream of links, 3-4-5 every day. Since I also receive quite a few direct emails for support/help... it's difficult for me to keep up with them all, read every issue individually and reply. Most of them are easy to reply to, so I'm wondering... what's the best way to move this from my plate to "_our plate_". Either the @Laravel-Backpack/team-members or the community at large?

Here's what I have in mind: I'd like to have an easy-to-use way (a chatroom, a GoogleDoc, or a place on BackpackForLaravel.com), where we can submit a link, and then "push" it to more people, so that somebody takes a look at it and replies. Here's what I have in mind:

(A) Create a bot for Gitter
(B) Create a bot for Discord
(C) Create a stream on BackpackForLaravel.com
(D) Post the links on [Github Discussions](https://github.com/Laravel-Backpack/CRUD/discussions)

Not really sure how to proceed on this one. But wanted to write it up, so we do something about it. I think it's an awesome user experience to be able to write anything, anywhere about our software, and in a matter of hours or a few day, someone to reply. I've heard people mention that on the internet "_it's amazing how tabacitu seems to be everywhere, all the time_", so it's something that we should keep doing, and doing even better, I think. But leaving it for me along to do... that's not sustainable. We've been getting more and more mentions, and it's beginning to take up a lot of time for just one person.

**Comment by pxpm** [comment]
My two cents on this, and I would LOVE to work on it:
- Create a public stream on `BackpackForLaravel`.
- Allow people to link their github/stackoverflow/reddit/twitter accts. 
- Create COOL Backpack Merch that people like to collect: mugs, pens, key holders, teddy bear with backpack logo! etc)
- People will help, and then !claim LINK_ID to earn "Backpack Stars" that could be redeemed as merchandise. 
- We could automatically link it to user (when answer is accepted etc), or user can !claim like I said for further verification.
- We can determine how much "Stars" the question is worth when adding it to the feed. 

It will help establish a brand, give some kind of "compensation" to the users that spend some of their time helping strangers on the internet. 

When I say earn mugs etc, we can also have different stuff like `Contribute 5€ to United Nations (1000 Stars)`, `50% discount on backpack license (5000 Stars)` wtv you get the point. 

If nobody else replies, atleast I can earn some stars myself to get a Backpack shirt to flex in the summer 👯‍♂️ 

But yeah, the first step, since you are already getting them, is to share it with backpack team, you will get them too, but atleast you know that maybe somebody from the team will answer 1 or 2 and help you with that. 

And yeah, sharing in gitter etc might help too, but I only see Dimitar Topalov or me helping around there. Some expontaneous from other people, but not much ...

**Comment by tabacitu** [comment]
Just created a channel on Discord where we can all post links. Let's see how that goes.
