### ISSUE TITLE
[Feature Request] Ability to show/hide count info

### ISSUE THREAD

**Issue by mamprogr** [Laravel-Backpack/ideas#191]
# Feature Request

### What's the feature you think Backpack should have?

I have items to show. But when the user is not an admin, I use closure to filter the items. I don't want non-admin users to see the total items count. So, I think we should have something like 
` CRUD::disableListInfo()` and ` CRUD::enableListInfo()`
![image](https://user-images.githubusercontent.com/734475/176205313-ca2c295c-fca2-447c-9663-798c8a9e4266.png)

### Have you already implemented a prototype solution, for your own project?

I am able to hide them using CSS but any user who knows how to inspect elements can see them.

### Do you see this as a core feature or an add-on?

I think it is important only if the system is multi-role.

**Comment by KevinCassier** [comment]
Hi! 
Any news about this please?

**Comment by pxpm** [comment]
Yes, PR is sent and is in review process by me and @jorgetwgroup !

We expect to finish during this/next week. 

If you are not subscribed to progress report newsletter (once a month), it's a good start to know when we ship it. 

You can follow the PR here:
https://github.com/Laravel-Backpack/CRUD/pull/4502

Closing this since I've now linked the PR to the issue, and we are doing it for sure. 

Cheers

**Comment by pxpm** [comment]
Well, I didn't do the best job here as I was lazy to pick the link. Thanks for sharing it @tabacitu 🙏

**Comment by KevinCassier** [comment]
:-) I subscribed ! Thanks
