### ISSUE TITLE
[Feature Request] Make filters groupable in tabs

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/ideas#211]
# Feature Request

### What's the feature you think Backpack should have?

Like fields have tabs, we think Backpack should allow use to group filters in tabs

### Have you already implemented a prototype solution, for your own project?

Ehm.. no, sorry

### Do you see this as a core feature or an add-on?

A core feature, eventually it could be ported only on PRO

**Comment by tabacitu** [comment]
Hmm... I don't quite see how that would be possible/good from a user perspective, @realtebo ... I mean... that would basically HIDE some of the filters behind a tab... which would be exactly the opposite of what we're trying to achieve here from a UI perspective. We tried filters under a {filter icon} at some point, eve {icon Filters} and our admins kept asking us "_how do you filter this table_", that's why we decided to leave them right there in the open...

I don't think we'll be adding this, sorry. But if you come up with a good UI solution, or more people gang up on me 😅 I'll happily reconsider.

Thanks for the suggestion @realtebo 🙏 We really appreciate your collaboration.

**Comment by realtebo** [comment]
I am little disappointed because also a normal form with tabs hides some fields .. so it's not so strange for a user.

We have a situation where we NEED 25 filters, some are very specific for some users so we would like to group filters for usare area.

Actually we did manually, again. This is good because your package allows us to customize almost 100% of what we need.

I disagree about this: adding an optional feature will not damage your  product, instead it will increase its value because of adding a new customization capability. Or not?

**Comment by tabacitu** [comment]
Hey @realtebo 

Thanks for the feedback 🙏 I might be wrong here (I often am 😅) but here's my thinking about it. 

### Importance

It seems to me like something YOU need, but 99% of all projects will not. We can't possibly cover 100% of all use cases, no software ever has, so we strive to cover MOST. And I think our current filters already cover "most" use cases. That's why I think it's not important for us to do this, it's a lot of work for something that would not help too many projects. So I disagree, I don't think this would add that much value to our product, sorry. 

It would add value to your project, I'm sure... but not a lot of other projects too. This is subject to change and feedback of course, so I'm open if more people tell us they'd find this useful, to reevaluate and reprioritize. But right now... this is the first time I hear about someone needing tabs in filters, sorry. So the "number of projects this would help" is 1, which is... very very low.

### Cost

This optional feature does make sense from your perspective, I get it. Because the cost of you building it is pretty small. But our cost to build it is much much bigger:
- we have to code it
- when we create Livewire components, to achieve feature-parity we'd have to add this feature there too
- when we add support for other themes (Tabler, etc) we will have to create interfaces for it there too
- then we have to keep and maintain all of the above, for years to come

This adds up to hundreds of hours of work, over the next 1-2 years. To help... how many projects? Not that many, right?

---

So that's why for these kinds of use cases... we recommend people just roll their own solutions, for their projects. Like you said, Backpack is fortunately very easy to customize, so you should be able to easily do that. 

Bottom line:
- The cost of you building it is small. And the impact is big (your projects need it).
- The cost of us building it is big. And the impact is minor (only 1 project needs it).

I hope you appreciate me explaining why thought process. Feel free to challenge it if you see any holes in my thinking.
I hope this helps us get on the same page in terms of what makes sense as a Backpack feature and what doesn't.

Please don't let this stop you from suggesting more ideas about how we can improve Backpack - I know you've contributed already over the years, and I hope you see that we treat your ideas the same way we treat ours - some we keep, some we don't 😀 It's just the way it is, we have to debate and challenge them before we implement them. We have limited resources.

----

Going further though... even if you build it for yourself... showing the filters in tabs... I don't think that's a good UI solution, to be honest... if filters are so many, and so important to that page... maybe they would make better sense to the left of the page? Like in e-commerce stores and such, when you filter products? That 
- would be more intuitive from a user perspective (I think)
- would allow for an infinite number of filters, basically (the page can get as long as needed)
- would allow filters to be split not in tabs, but in headings... so that all filters are visible all the time
 
Just my 2 cents.
Cheers!
