### ISSUE TITLE
[Enhancement] ListOperation calculates total without local scopes

### ISSUE THREAD

**Issue by tkerns** [Laravel-Backpack/ideas#59]
# Bug report

### What I did
On the list view, if you apply a scope, or a where in the list setup like this
`$this->crud->addClause('active'); // apply a local scope`
and before I have filtered the record set in the UI,

### What I expected to happen

I would expect it to show something like this at the top.

**Showing 1 to 10 of 730 entries**

and then when I filter using the search box, or a filter, for it to tell me the results have been filtered like this

**Showing 1 to 10 of 250 entries (filtered from 730 total entries)**

### What happened

Instead, it show me this:

**Showing 1 to 10 of 730 entries (filtered from 1,021 total entries)**

even before filtering, just because I applied the scope in the setupListOperation

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.3.14 (cli) (built: Jan 21 2020 13:15:55) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.14, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
laravel/framework                     v6.17.1            The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                         4.0.41             Quickly build an admin interfaces using Laravel 6, CoreUI...
backpack/generators                   2.0.6              Generate files for laravel projects

**Comment by tabacitu** [comment]
Thanks @zachweix 

Hmm come to think of it, for those two things:
```php
        $totalRows = $this->crud->model->count();
        $filteredRows = $this->crud->count();
```
were could just call a method on the CrudPanel object, say `getTotalRowsCount()` and `getFilteredRowsCount()`, if it exists, and fall back to what we have now if it does't. That would allow developers to easily overwrite the totals in particular use cases, without having to overwrite the entire `search()` method, [using Macros](https://backpackforlaravel.com/docs/4.1/crud-operations#adding-methods-to-the-crudpanel-object);

So by changing it to:

```diff
-        $totalRows = $this->crud->model->count();
+        $totalRows = method_exists($this->crud, 'getTotalRowsCount') ? $this->crud->getTotalRowsCount() : $this->crud->model->count();
-        $filteredRows = $this->crud->count();
+        $filteredRows = method_exists($this->crud, 'getFilteredRowsCount') ? $this->crud->getFilteredRowsCount() : $this->crud->count();
```

The developer would be able to do this in his `setup()` (or somewhere more global):

```php
       $this->crud->macro('getTotalRowsCount', function() {
            return $this->model->count();
        });
       $this->crud->macro('getFilteredRowsCount', function() {
            return $this->count();
        });
```

I think `CrudPanel` is a better place for those methods, rather than the `CrudController`. 
What do you think @tkerns & @zachweix ?

**Comment by tkerns** [comment]
I like it!  I never liked the idea of having to overwrite the search method, so I usually just lived with the inaccurate numbers.
This would be perfect, allowing me to use a method on those panels where I am using query scopes.
I appreciate you keeping this on your mind!

**Comment by quanengineering** [comment]
I'm looking forward to this feature because the total rows count needs to be customized in some cases.

**Comment by pxpm** [comment]
This will be added here: https://github.com/Laravel-Backpack/CRUD/pull/4502
